services:
  builder:
    image: builder
    build:
      context: .
      dockerfile: docker/builder.Dockerfile
  website:
    build:
      no_cache: true
      context: .
      args:
        SERVER_NAME:
      dockerfile: docker/website.Dockerfile
    ports:
      - ${PORT}:80
    depends_on:
      - builder