services:
  builder:
    build:
      context: .
      dockerfile: docker/builder.Dockerfile
  website:
    build:
      no_cache: true
      context: .
      dockerfile: docker/website.Dockerfile
      additional_contexts:
        builder: "service:builder"
    ports:
      - 8080:80